server:
  port: ${GATEWAY_SERVICE_PORT:8080}

gateway:
  api-key: ${GATEWAY_API_KEY:secret-key}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: session-service
          uri: http://localhost:${SESSION_SERVICE_PORT:8081}
          predicates:
            - Path=/api/v1/sessions/**

        - id: message-service
          uri: http://localhost:${MESSAGE_SERVICE_PORT:8082}
          predicates:
            - Path=/api/v1/sessions/*/messages/**

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.example.rag: ${LOGGING_LEVEL_COM_EXAMPLE_RAG:DEBUG}
